go.mod
=> chore(otlpcol): modify module name

go.mod
=> chore(otlpcol): rollback module name

internal/data/traceid.go
**Description:** fix unmarshal error.
=> chore(open telemetry-collector): fix unmarshal error

handler/tagctx/processinfo/util.go
=> chore(): split host and port

handler/tagctx/processinfo/util.go
=> chore(): fix cc value

handler/tagctx/processinfo/util.go
=> chore(): fix cc ip

handler/tagctx/processinfo/grpchandler.go, handler/tagctx/processinfo/httphandler.go
**Description:** 
chore(): fix get cmd and pid error
=> chore(): fix get cmd and pid error

handler/tagctx/processinfo/util.go
**Description:** 
chore(): fix tcp4 to tic
=> chore(): fix tcp4 to tic

handler/tagctx/processinfo/grpchandler.go, handler/tagctx/processinfo/httphandler.go, handler/tagctx/processinfo/util.go, service/telemetry.go
**Description:** 
chore(): fix pid logical
=> chore(): fix pid logical

go.mod, go.sum
**Description:** 
upgrade gopsutil version for m1
=> chore(): 提交gopsutil版本

translator/trace/zipkin/zipkinv2_to_traces.go
**Description:**
flink can not accept zero timestamp, fix it
=> chore(): flink can not accept zero timestamp, fix it

service/telemetry.go
**Description:**  
remove the process view because it can not stop when application stop.
=> chore(): 移除进程信息采集

exporter/kafkaexporter/factory.go, exporter/kafkaexporter/kafka_exporter.go, exporter/kafkaexporter/marshaller.go, exporter/kafkaexporter/otlp_marshaller.go
=> feat(kafkaexporter): add logs exporter

exporter/exporterhelper/queued_retry.go
=> 添加kafka错误信息打印

receiver/hostmetricsreceiver/internal/metadata/generated_metrics.go, receiver/hostmetricsreceiver/internal/scraper/processscraper/config.go, receiver/hostmetricsreceiver/internal/scraper/processscraper/process.go, receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper.go, receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper_linux.go, receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper_others.go, receiver/hostmetricsreceiver/internal/scraper/processscraper/process_scraper_windows.go, service/telemetry.go
=> chore(): 返回进程名称标签

exporter/kafkaexporter/config.go, exporter/kafkaexporter/kafka_exporter.go, go.mod, go.sum
=> feat(kafkaexporter): add message key for log kafka exporter

exporter/kafkaexporter/factory_test.go, exporter/kafkaexporter/jaeger_marshaller.go, exporter/kafkaexporter/jaeger_marshaller_test.go, exporter/kafkaexporter/kafka_exporter.go, exporter/kafkaexporter/kafka_exporter_test.go, exporter/kafkaexporter/marshaller.go, exporter/kafkaexporter/otlp_marshaller.go, exporter/kafkaexporter/otlp_marshaller_test.go, go.mod
=> feat(kafkaexporter): add message key for trace kafka exporter

consumer/pdata/trace.go, exporter/kafkaexporter/otlp_marshaller.go
=> feat(kafkaexporter): update otlpTracesPbMarshaller

translator/trace/zipkin/zipkinv2_to_traces.go
=> chore(console): 控制台链路追踪添加status code & message

receiver/kafkareceiver/factory.go, receiver/kafkareceiver/kafka_receiver.go, receiver/kafkareceiver/unmarshaller.go
=> feat(kafkareceiver): add logs unmarshaller
